name: Cypress Tests

on: [push]

jobs: 
  cypress-electron-tests:
    runs-on: ubuntu-latest
    steps:
      - name: get code
        uses: actions/checkout@v4.1.7

      - name: install dependence
        run: yarn install

      - name: Run E2E tests on Cypress
        run: yarn cypress run
    
  
